apiVersion: apps/ver1
kind: Deployment
Metadata:
  name: nginx-deployment
  labels:
spec:
  replicas: 2
  selector:
  matchLabels:
    app: nginx
    template:
      metadata:
      labels:
        app: nginx
  spec:
  containers:
    - name: nginx
      image: nginx:1.16
      ports:
      containerport: 8080
